### ISSUE TITLE
Save the font correctly

### ISSUE THREAD

**Issue by Fuzzyma** [joshmarinacci/node-pureimage#50] opened 2018-01-21 20:46 UTC
At the moment the code for setting the font is this:

```js
        Object.defineProperty(this,'font', {
            get: function() {

            },
            set: function(val) {
                val = val.trim();
                var n = val.indexOf(' ');
                var size = parseInt(val.slice(0,n));
                var name = val.slice(n);
                this._font.family = name;
                this._font.size = size;
            }
        });
```

Instead it should be this to have a clean name of the text and not something like ` \'OpenSans\'` (mind the `'` and the space)

```js
        Object.defineProperty(this,'font', {
            get: function() {

            },
            set: function(val) {
                val = val.replace(/\s+/g, '');
                var n = val.indexOf(' ');
                var size = parseInt(val.slice(0,n));
                var name = val.slice(n+1).replace(/'/g, '');
                this._font.family = name;
                this._font.size = size;
            }
        });
```

This results in a clean font `OpenSans`

**Comment by robertmain** [comment] 2018-01-21 22:17
This feels like a duplicate of #51 (and is possibly related to #37?)

**Comment by Fuzzyma** [comment] 2018-01-22 00:10
#51 is no duplicate (I opened both issues). This are 2 seperate problems. I think that's really clear from what I wrote in every issue.
However the other issue you mentioned is definitely related. My code sample would solve that problem, too.

**Comment by robertmain** [comment] 2018-01-22 00:23
If your code sample fixes it - why not open a PR with it? The diff produced by a PR gives a clearer picture of what changed than a code snippet in a GH issue...

**Comment by Fuzzyma** [comment] 2018-01-22 00:27
Because I simply had no time to open a PR. Beside this, the changes I made can be easily seen especially for the one who wrote this code.

**Comment by robertmain** [comment] 2018-01-22 20:18
>the changes I made can be easily seen

No. No they can't. That's exactly my point Sure, I can sit and play a game of "spot the difference" between the two code snippets, but I too  _"simply have no time to open a PR"_ right now. Also, the code has changed between the code sample you pasted above, and the current tip of `master`...so now I would have to do a 3-way diff between the two snippets you posted and `master` (hint: _I'm not going to_). This means that a change that "can be easily seen" is not so obvious for others.

Finally, your original issue leaves certain things to be desired. For example, you mentioned _"a clean font"_. Right now, I tested what's currently in `master` as follows:

```js
const pureimage = require('pureimage');

const context = pureimage.make(200, 200)
                         .getContext('2d');

context.font = '48px Open Sans';

console.log(context._font);
```

which gave me the following:

```js
{ family: 'Open Sans', size: 48 }
```

Aside from the space between "Open" and "Sans", I'm not seeing any other leading or trailing spaces. There was work done on that particular piece of code @fmsy in #41 and #37, so unless I've overlookd something - it's possible that the issue has already been fixed.

As it is - it might be a while before this gets looked into, since myself and the other _volunteers_ who maintain this library are somewhat busy at present...

**Closed** 2022-06-26 19:09 UTC
Labels: font
